[project]
name = "fastrepo"
version = "0.1.0"
description = "Add a short description here"
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
fmt = "ruff format"
conda-forge = "python py/split_repo.py --channel conda-forge"
robostack = "python py/split_repo.py --channel robostack --all-subdirs"
start = "python py/split_repo.py"

[dependencies]
requests = ">=2.31.0,<2.32"
python = ">=3.12.3,<3.13"
boto3 = ">=1.34.90,<1.35"
aiohttp = ">=3.9.5,<3.10"
pyzstd = ">=0.15.9,<0.16"
zstandard = ">=0.22.0,<0.23"
tqdm = ">=4.66.2,<4.67"
msgpack-python = ">=1.0.7,<1.1"
ruff = ">=0.4.2,<0.5"
rich = ">=13.7.1,<13.8"
