name: Mirror repodata

on:
  workflow_dispatch: null
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"

jobs:
  upload:
    strategy:
      matrix:
        include:
          - channel: conda-forge
            subdirs: linux-64,linux-aarch64,linux-ppc64le,osx-arm64,osx-64,win-64,win-arm64,noarch
          - channel: bioconda
            subdirs: linux-64,osx-64,win-64,noarch,linux-aarch64
          - channel: robostack
            subdirs: linux-64,linux-aarch64,osx-64,osx-arm64,win-64,noarch
          - channel: robostack-staging
            subdirs: linux-64,linux-aarch64,osx-64,osx-arm64,win-64,noarch
          - channel: robostack-humble
            subdirs: linux-64,linux-aarch64,osx-64,osx-arm64,win-64,noarch

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.6.0
        with:
          pixi-version: v0.20.1
          cache: true
      - env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          pixi run start --channel ${{ matrix.channel }} --subdirs ${{ matrix.subdirs }}
